Adding files FROM bash to git

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,16 +44,32 @@ jobs:
           sudo mv allure-2.27.0 /opt/allure
           sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
 
-      - name: Run Pytest and collect Allure results
-        run: |
-          source venv/bin/activate
-          python -m pytest --alluredir=Reports || true
-          allure generate --single-file -o Reports || true
-
+          - name: Run Pytest and collect Allure results
+          run: |
+            source venv/bin/activate
+            python -m pytest --alluredir=Reports || true
+            allure generate --clean --single-file -o Reports || true
+        
       - name: Move single HTML report to docs
         run: |
           mkdir -p docs
-          mv Reports/index.html docs/
+          if [ -f Reports/index.html ]; then
+            mv Reports/index.html docs/
+          else
+            echo "index.html not found, skipping move step"
+          fi
+        
+
+      # - name: Run Pytest and collect Allure results
+      #   run: |
+      #     source venv/bin/activate
+      #     python -m pytest --alluredir=Reports || true
+      #     allure generate --single-file -o Reports || true
+
+      # - name: Move single HTML report to docs
+      #   run: |
+      #     mkdir -p docs
+      #     mv Reports/index.html docs/
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
